// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore8TestApplication.Data;

#nullable disable

namespace NetCore8TestApplication.Migrations
{
    [DbContext(typeof(FirstDatabaseContext))]
    [Migration("20211113073353_Inititial")]
    partial class Inititial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NetCore8TestApplication.Data.FirstDataModel", b =>
                {
                    b.Property<int>("FirstDataModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirstDataModelID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirstDataModelID");

                    b.ToTable("FirstDataModels");

                    b.HasData(
                        new
                        {
                            FirstDataModelID = 1,
                            Name = "First name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
