// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreTestApplication.Data;

namespace NetCoreTestApplication.Migrations
{
    [DbContext(typeof(FirstDatabaseContext))]
    [Migration("20190907102207_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreTestApplication.Data.FirstDataModel", b =>
                {
                    b.Property<int>("FirstDataModelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.HasKey("FirstDataModelID");

                    b.ToTable("FirstDataModels");

                    b.HasData(
                        new { FirstDataModelID = 1, LastName = "Last name", Name = "First name" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
