trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectPath: './NetCore6.0TestApplication/NetCore6.0TestApplication/NetCore6.0TestApplication.csproj'
  libraryPath: './NetCore6.0TestApplication/NetCore6.0TestLibrary/NetCore6.0TestLibrary.csproj'
  efToolVersion: '6.*'
  netSdkVersion: '6.0.100'

steps:

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk $(netSdkVersion)'
  inputs:
    version: $(netSdkVersion)

- script: 'dotnet restore $(projectPath)'
  displayName: Restore

- script: 'dotnet build $(projectPath) --configuration $(buildConfiguration)'
  displayName: Build

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - Library project'
  inputs:
    projectpath: $(libraryPath)
    databasecontexts: |
     LibraryDatabaseContext
     InternalLibraryDatabaseContext
    startupprojectpath: $(projectPath)
    installdependencies: true
    eftoolversion: '$(efToolVersion)'

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - Main project'
  inputs:
    projectpath: $(projectPath)
    databasecontexts: FirstDatabaseContext
    installdependencies: false

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - All in one'
  inputs:
    projectpath: $(projectPath)
    databasecontexts: |
     FirstDatabaseContext
     SecondDatabaseContext
     LibraryDatabaseContext
     InternalLibraryDatabaseContext
    installdependencies: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'

